name: R CMD Check & Build

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  R-CMD-check:
    outputs:
      full_version: ${{ steps.dynamic_version.outputs.FULL_VERSION }}
      pkg_file: ${{ steps.build.outputs.PKG_FILE }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Read version from .ver file
        id: get_version
        run: echo "VERSION=$(cat .ver)" >> $GITHUB_OUTPUT

      - name: Get short commit SHA
        id: get_sha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Construct dynamic version string
        id: dynamic_version
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="${{ steps.get_version.outputs.VERSION }}.${{ steps.get_sha.outputs.SHA }}"
          fi
          echo "FULL_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update DESCRIPTION file with dynamic version
        run: |
          echo "Using version for DESCRIPTION: ${{ steps.dynamic_version.outputs.FULL_VERSION }}"
          sed -i "s/^Version: .*/Version: ${{ steps.dynamic_version.outputs.FULL_VERSION }}/" DESCRIPTION
          echo "DESCRIPTION file after update:"
          cat DESCRIPTION

      - name: Install system dependencies and packrat
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            packrat

      - name: Install rcmdcheck
        run: Rscript -e "install.packages('rcmdcheck', repos = 'https://cloud.r-project.org')"

      - name: Restore R package dependencies (packrat)
        run: Rscript -e "packrat::restore()"

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: Build package
        id: build
        run: |
          R CMD build .
          PKG_FILE=$(ls *.tar.gz)
          echo "PKG_FILE=$PKG_FILE" >> $GITHUB_OUTPUT
          echo "Built package file: $PKG_FILE"

      - name: Upload package tarball
        uses: actions/upload-artifact@v4
        with:
          name: processcontrol-${{ steps.dynamic_version.outputs.FULL_VERSION }}
          path: ${{ steps.build.outputs.PKG_FILE }}

  release:
    needs: R-CMD-check
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: processcontrol-${{ needs.R-CMD-check.outputs.full_version }}
          path: dist

      - name: List packaged files
        run: ls -R dist

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: processcontrol ${{ needs.R-CMD-check.outputs.full_version }}
          files: dist/${{ needs.R-CMD-check.outputs.pkg_file }}
